<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

Dict::Add('EN US', 'English', 'English', array(
    'Class:Asset' => 'Asset',
    'Class:Asset+' => 'An item that is owned and has value',
    'Class:Asset/Attribute:penempatan' => 'penempatan',
    'Class:Asset/Attribute:asset_name' => 'Asset Name',
    'Class:Asset/Attribute:asset_tag' => 'Asset Tag',
    'Class:Asset/Attribute:serial' => 'Serial',
    'Class:Asset/Attribute:model' => 'Model',
    'Class:Asset/Attribute:model_no' => 'Model Number',
    'Class:Asset/Attribute:category' => 'Category',
    'Class:Asset/Attribute:statuss' => 'Status',
    'Class:Asset/Attribute:checked_out_to' => 'Checked Out To',
    'Class:Asset/Attribute:employee_number' => 'Employee Number',
    'Class:Asset/Attribute:location' => 'Location',
    'Class:Asset/Attribute:default_location' => 'Default Location',
    'Class:Asset/Attribute:manufacturer' => 'Manufacturer',
    'Class:Asset/Attribute:supplier' => 'Supplier',
    'Class:Asset/Attribute:purchase_dates' => 'Purchase Date',
    'Class:Asset/Attribute:age' => 'Age',
    'Class:Asset/Attribute:purchase_cost' => 'Purchase Cost',
    'Class:Asset/Attribute:current_value' => 'Current Value',
    'Class:Asset/Attribute:order_number' => 'Order Number',
    'Class:Asset/Attribute:eol_rate' => 'End of Life Rate',
    'Class:Asset/Attribute:eol_date' => 'End of Life Date',
    'Class:Asset/Attribute:warranty' => 'Warranty',
    'Class:Asset/Attribute:warranty_expires' => 'Warranty Expires',
    'Class:Asset/Attribute:requestable' => 'Requestable',
    'Class:Asset/Attribute:notes' => 'Notes',
    'Class:Asset/Attribute:checkouts' => 'Checkouts',
    'Class:Asset/Attribute:checkins' => 'Checkins',
    'Class:Asset/Attribute:requests' => 'Requests',
    'Class:Asset/Attribute:created_at' => 'Created At',
    'Class:Asset/Attribute:updated_at' => 'Updated At',
    'Class:Asset/Attribute:checkout_date' => 'Checkout Date',
    'Class:Asset/Attribute:last_checkin_date' => 'Last Checkin Date',
    'Class:Asset/Attribute:expected_checkin_date' => 'Expected Checkin Date',
    'Class:Asset/Attribute:last_audit' => 'Last Audit',
    'Class:Asset/Attribute:next_audit_date' => 'Next Audit Date',
    'Class:Asset/Attribute:byod' => 'BYOD',
    'Class:Asset/Attribute:components_accessories' => 'Components & Accessories',
    'Class:Asset/Attribute:device_hostname' => 'Device Hostname',
    'Class:Asset/Attribute:serial_no' => 'Serial Number',
    'Class:Asset/Attribute:asset_location' => 'Asset Location',
    'Class:Asset/Attribute:ip_address' => 'IP Address',
    'Class:Asset/Attribute:site_id' => 'Site ID',
    'Class:Asset/Attribute:site_name' => 'Site Name',
    'Class:Asset/Attribute:asset_status' => 'Asset Status',
    'Class:Asset/Attribute:operating_system' => 'Operating System',
    'Class:Asset/Attribute:software_installed' => 'Software Installed',
    'Class:Asset/Attribute:start_warranty_period' => 'Start Warranty Period',
    'Class:Asset/Attribute:end_warranty_period' => 'End Warranty Period',
    'Class:Asset/Attribute:delivery_date' => 'Delivery Date',
    'Class:Asset/Attribute:official_government_order_no' => 'Official Government Order Number',
    'Class:Asset/Attribute:type_brand_model' => 'Type Brand Model',
    'Class:Asset/Attribute:price_per_unit' => 'Price Per Unit',
    'Class:Asset/Attribute:supplier_name' => 'Supplier Name',
    'Class:Asset/Attribute:region' => 'Region',
));
?>
